version: '3'

services:
  codemonkey-database:
    #image: codemonkey-database
    image: iacobucci/codemonkey-database
    container_name: codemonkey-database-compose
    networks:
      - codemonkey-network

  codemonkey-backend:
    #image: codemonkey-backend
    image: iacobucci/codemonkey-backend
    environment:
      - BACKEND_DATABASE_USER=admin
      - BACKEND_DATABASE_PASSWORD=password
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=4c61fe7c0395dc5e96de25ed0f093a4f
    container_name: codemonkey-backend-compose
    depends_on:
      - codemonkey-database
    networks:
      - codemonkey-network

  codemonkey-frontend:
    #image: codemonkey-frontend
    image: iacobucci/codemonkey-frontend
    container_name: codemonkey-frontend-compose
    depends_on:
      - codemonkey-backend
    networks:
      - codemonkey-network

  codemonkey-nginx:
    #image: codemonkey-nginx
    image: iacobucci/codemonkey-nginx
    container_name: codemonkey-nginx-compose
    ports:
      - '8081:80'
    depends_on:
      - codemonkey-backend
      - codemonkey-frontend
    networks:
      - codemonkey-network

networks:
  codemonkey-network:
    driver: bridge
