version: '3.8'

services:
  codemonkey-backend:
    image: codemonkey-backend
    container_name: codemonkey-backend-image
    depends_on:
      - codemonkey-database

  codemonkey-frontend:
    image: codemonkey-frontend
    container_name: codemonkey-frontend-image
    depends_on:
      - codemonkey-backend

  codemonkey-database:
    image: codemonkey-database
    container_name: codemonkey-database-image
    ports:
      - '5432:5432'

  nginx:
    image: nginx:latest
    container_name: codemonkey-nginx
    ports:
      # release
      # - '80:80'
      # development
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - codemonkey-backend
      - codemonkey-frontend
