version: '3'

services:
  codemonkey-nginx:
    image: codemonkey-nginx
    container_name: codemonkey-nginx-compose
    ports:
      - '8080:80'
    networks:
      - codemonkey-network

  codemonkey-database:
    image: codemonkey-database
    # image: codemonkey.azurecr.io/codemonkey-database:latest
    container_name: codemonkey-database-compose
    depends_on:
      - codemonkey-nginx
    ports:
      - '5432:5432'
    networks:
      - codemonkey-network

  codemonkey-backend:
    image: codemonkey-backend
    # image: codemonkey.azurecr.io/codemonkey-backend:latest
    environment:
      - BACKEND_DATABASE_USER=admin
      - BACKEND_DATABASE_PASSWORD=password
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=4c61fe7c0395dc5e96de25ed0f093a4f
    container_name: codemonkey-backend-compose
    depends_on:
      - codemonkey-database
    networks:
      - codemonkey-network

  codemonkey-frontend:
    image: codemonkey-frontend
    # image: codemonkey.azurecr.io/codemonkey-frontend:latest
    container_name: codemonkey-frontend-compose
    depends_on:
      - codemonkey-backend
    networks:
      - codemonkey-network

networks:
  codemonkey-network:
    driver: bridge
